site_name: Zeta Docs
site_url: 'https://zeta.apac.ai'
site_author: APAC AI
site_description: >-
  Create Ultra-Powerful Multi-Modality Models Seamlessly and Efficiently in as
  minimal lines of code as possible.
repo_name: kyegomez/zeta
repo_url: 'https://github.com/kyegomez/zeta'
edit_uri: 'https://github.com/kyegomez/"zeta/tree/main/docs'
copyright: APAC Corp 2023. All rights reserved.
plugins:
  - glightbox
  - search
extra_css:
  - docs/assets/css/extra.css
extra:
  social:
    - icon: fontawesome/solid/house
      link: assets/img/zeta-logo.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Zeta/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/"Zeta/
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/img/zeta-logo.png
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
  - Home:
      - Overview: "index.md"
      - Contributing: "contributing.md"
  - Zeta:
      - Overview: "zeta/index.md"
      - zeta.nn:
          - zeta.nn.biases:
              - Xpos: "zeta/nn/biases/xpos.md"
              - RelativePositionBias: "zeta/nn/biases/relative_bias.md"
              - AlibiPositionalBias: "zeta/nn/biases/alibi.md"
              - DynamicPositionBias: "zeta/nn/biases/dynamic.md"
          - zeta.nn.embeddings:
              - MultiWay: "zeta/nn/embeddings/multiway.md"
              - RotaryEmbeddings: "zeta/nn/embeddings/rope.md"
              - TruncatedRotaryEmbedding: "zeta/nn/embeddings/truncated_rope.md"
              - PositionalEmbedding: "zeta/nn/embeddings/positional_embeddings.md"
              - XPOS: "zeta/nn/embeddings/xpos.md"
              - YarnEmbedding: "zeta/nn/embeddings/yarn.md"
              - VisionEmbedding: "zeta/nn/embeddings/vis_emb.md"
              - SinusoidalEmbeddings: "zeta/nn/embeddings/sinusoidal.md"
              - PatchEmbeddings: "zeta/nn/embeddings/patch_embeddings.md"
              - PositionInterpolationEmbeddings: "zeta/nn/pi.md"
          - zeta.nn.modules:
              - Lora: "zeta/nn/modules/lora.md"
              - TokenLearner: "zeta/nn/modules/token_learner.md"
              - DynamicModule: "zeta/nn/modules/dm.md"
              - AdaptiveParameterList: "zeta/nn/modules/adaptive.md"
              - RMSNorm: "zeta/nn/modules/rms_norm.md"
              - MLP: "zeta/nn/modules/mlp.md"
              - mbconv: "zeta/nn/modules/mbconv.md"
              - LayerNorm: "zeta/nn/modules/layernorm.md"
              - Ether: "zeta/nn/modules/ether.md"
              - Exo: "zeta/nn/modules/exo.md"
              - AdaptiveConv3DMod: "zeta/nn/modules/adaptive_conv.md"
              - TimeUpSample2x: "zeta/nn/modules/time_up_sample.md"
              - SigLipLoss: "zeta/nn/modules/siglip.md"
              - SimpleFeedFoward: "zeta/nn/modules/simple_feedback.md"
              - Unet: "zeta/nn/modules/unet.md"
              - VisualExpert: "zeta/nn/modules/visual_expert.md"
              - FeedForward: "zeta/nn/modules/feedforward.md"
              - BasicHebbianGRUModel: "zeta/nn/modules/hebbian.md"
              - MultiModalAdapterDenseNetwork: "zeta/nn/modules/mm_adapter.md"
              - CustomMLP: "zeta/nn/modules/custom_mlp.md"
              - PolymorphicNeuronLayer: "zeta/nn/modules/polymorphic_activation.md"
          - zeta.nn.attention:
              - FlashAttention: "zeta/nn/attention/flash_attention.md"
              - MultiQueryAttention: "zeta/nn/attention/multiquery.md"
              - MultiheadAttention: "zeta/nn/attention/multihead.md"
              - FlashAttentionTwo: "zeta/nn/attention/flash2.md"
              - BaseAttention: "zeta/nn/attention/base.md"
              - LocalAttention: "zeta/nn/attention/local.md"
              - LocalMHA: "zeta/nn/attention/localmha.md"
              - MixtureOfAttention: "zeta/nn/attention/mixture_of_attention.md"
              - MixtureOfAutoregressiveAttention: "zeta/nn/attention/mixture_of_attention_ar.md"
              - SparseAttention: "zeta/nn/attention/sparse_attn.md"
          - zeta.structs:
              - Decoder: "zeta/nn/architecture/decoder.md"
              - Transformer: "zeta/nn/architecture/transformer.md"
              - TransformerBlock: "zeta/nn/architecture/transformerblock.md"
              - VideoTokenizer: "zeta/nn/architecture/video_tokenizer.md"
          - zeta.training.loss:
              - Nebula: "zeta/training/nebula.md"
          - zeta.training.optimizers:
              - DecoupledLionW: "zeta/training/optimizers/decoupled_lion.md"
              - SophiaG: "zeta/training/optimizers/sophia.md"
      - zeta.tokenizers:
          - MultiModalTokenizer: "zeta/tokenizers/multi_modal_tokenizer.md"
          - LanguageTokenizerGPTX: "zeta/tokenizers/language_tokenizer.md"
          - SentencePieceTokenizer: "zeta/tokenizers/sentencepiece.md"
          - TokenMonster: "zeta/tokenizers/token_monster.md"
      - zeta.utils:
          - main: "zeta/utils/main.md"
          - track_cuda_memory_usage: "zeta/utils/track_cuda_memory.md"
      - zeta.ops:
          - main: "zeta/ops/main.md"
          - softmaxes: "zeta/ops/softmaxes.md"
      - zeta.optim:
          - StableAdamWUnfused: "zeta/optims/adamw.md"
          - GradientAscent: "zeta/optims/ga.md"
      - zeta.training:
          - fsdp: "zeta/training/fsdp.md"
          - ParallelWrapper: "zeta/training/parallel_wrapper.md"
          - train: "zeta/training/train.md"
      - zeta.quant:
          - QUIK: "zeta/quant/quik.md"
          - BitLinear: "zeta/quant/bitlinear.md"
          - niva: "zeta/quant/niva.md"
  - Examples:
    - Overview: "examples/index.md"
  - Product:
    - Overview: "zeta/product/product_ideas.md"
    - Zetahub: "zeta/product/zetahub.md"
  - Blog:
    - Introduction: "blog/introduction_to_zeta.md"