[tool.poetry]
name = "zetascale"
version = "0.0.4"
description = "Transformers at zeta scales"
authors = ["Zeta Team <kye@apac.ai>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kyegomez/zeta"
keywords = ["Transformers", "zeta scale"]
classifiers = [
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.8"
fairscale = "0.4.0"
timm = "0.6.13"
triton = "*"
pytest = "*"
einops = "*"


[tool.poetry.packages]
include = "zeta/**/*" 


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

